return {
	RAW_GEAR_ASSETS_PATH = "assets",
	GEAR_PATH = "src/gear",

	SCRIPTS_PATH = "scripts",
	SOURCE_PATH = "src",

	LUAU_PACKAGES_PATH = "LuauPackages",

	LUTE_BATTERIES = {
		"cli.luau",
		"pp.luau",
		"richterm.luau",
	},
	LUTE_BATTERIES_COMMIT = "6a8e5f0",
	LUTE_BATTERIES_PATH = "LuauPackages/batteries",

	ROBLOX_UNIT_TESTING_PLACE_ID = 87060735635538,
	ROBLOX_UNIT_TESTING_UNIVERSE_ID = 8046529594,
}
