return {
	RAW_GEAR_ASSETS_PATH = "assets",
	GEAR_PATH = "src/gear",
	GEAR_INVENTORY_PATH = "src/AllGear.csv",

	SCRIPTS_PATH = "scripts",
	SITE_PATH = "site",
	SOURCE_PATH = "src",

	TESTS_PROJECT_PATH = "tests.project.json",

	LUAU_PACKAGES_PATH = "LuauPackages",

	LUTE_BATTERIES = {
		"cli.luau",
		"pp.luau",
		"richterm.luau",
	},
	LUTE_BATTERIES_COMMIT = "6a8e5f0",
	LUTE_BATTERIES_PATH = "LuauPackages/batteries",

	ROBLOX_UNIT_TESTING_PLACE_ID = "74265882577854",
	ROBLOX_UNIT_TESTING_UNIVERSE_ID = "7943381724",
}
