[assets.default]
name = "Space Sandwich"
description = ""
model = "build.rbxm"
environment = "prod"

[environments.prod]
creatorId = 8701739411
creatorType = "User"
universeId = 7943381724
placeId = 74265882577854
