--Rescripted by Luckymaxer

Content = {
	Cursors ={
		Normal = "http://www.roblox.com/asset/?id=94154683", --black
		Target = "http://www.roblox.com/asset/?id=94154829", --red
		ReloadStatic1 = "http://www.roblox.com/asset/?id=94155503",
		ReloadStatic2 = "http://www.roblox.com/asset/?id=94155569",
	},
	NumberImages = {
		[0] = 94128401,
		[1] = 94128421,
		[2] = 94128434,
		[3] = 94128446,
		[4] = 94128466,
		[5] = 94128485,
		[6] = 94128496,
		[7] = 94128523,
		[8] = 94128538,
		[9] = 97903893,
	},
}

return Content